// apps/angular/src/app/app.component.ts
import { Component } from '@angular/core'
import { ISpace, SpaceService } from '@flatfile/angular-sdk'
import { workbook } from './workbook'
import { listener } from './listener'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  showSpace: boolean = false

  constructor(private spaceService: SpaceService) {}

  toggleSpace() {
    this.spaceService.OpenEmbed()
    this.showSpace = !this.showSpace
  }

  closeSpace() {
    this.showSpace = false
  }

  spaceProps: ISpace = {
    name: 'Trste!',
    publishableKey: 'pk_ixtxE3L9iVMYgaaxePSn5hGxLffNJhiS',
    workbook,
    listener,
    userInfo: {
      name: 'my space name',
    },
    spaceInfo: {
      name: 'my space name',
    },
    displayAsModal: false,
    spaceBody: {
      metadata: {
        random: 'param',
      },
    },
    sidebarConfig: {
      showSidebar: true,
    },
  }
}

<main class="main">
  <div class="description">
    <button (click)="toggleSpace()">
      {{ showSpace ? 'Close' : 'Open' }} space
    </button>
  </div>
  <div class="spaceWrapper" *ngIf="showSpace">
    <flatfile-space [spaceProps]="spaceProps"></flatfile-space>
  </div>
</main>

// apps/vue/src/App.vue
<script lang="jsx">
import { ref, onMounted, h, defineComponent } from 'vue'
import { initializeFlatfile } from '@flatfile/vue'
import { workbook } from './config'
import { listener } from './listener'

const SPACE_ID = 'us_sp_12314'
const ENVIRONMENT_ID = 'us_env_1234'

export default defineComponent({
  setup() {
    const publishableKey = 'pk_ixtxE3L9iVMYgaaxePSn5hGxLffNJhiS'
    const spaceProps = ref({
      name: 'Trste!',
      publishableKey,
      workbook,
      listener,
      document: {
        title: 'Instructions',
        body:
          '# Supported file types\n' +
          '---\n' +
          'Please only import CSV and Excel files',
        defaultPage: true,
      },

      themeConfig: { primaryColor: '#546a76', textColor: '#fff' },
      userInfo: {
        name: 'my space name',
      },
      spaceInfo: {
        name: 'my space name',
      },
      displayAsModal: true,
      spaceBody: {
        metadata: {
          sidebarConfig: {
            showSidebar: true,
          },
        },
      },
    })

    const { Space, OpenEmbed } = initializeFlatfile(spaceProps.value)

    const toggleSpace = () => {
      OpenEmbed()
    }

    return {
      toggleSpace,
      Space,
    }
  },
  render(props, ctx) {
    const Space = props.Space

    return (
      <div>
        <div class="description">
          <button onClick={props.toggleSpace}>Open space</button>
        </div>

        <Space />
      </div>
    )
  },
})
</script>
