// packages/react/src/hooks/useSpace.tsx
import React, { JSX, useEffect, useState } from 'react'
import DefaultError from '../components/Error'
import Space from '../components/Space'
import Spinner from '../components/Spinner'
import { ReusedSpaceWithAccessToken, SimpleOnboarding, State, getSpace, initializeSpace } from '@flatfile/embedded-utils'
import { IReactSpaceProps } from '../types'

export const useSpace = (props: IReactSpaceProps): JSX.Element | null => {
  const {
    error: ErrorElement,
    errorTitle,
    loading: LoadingElement,
    apiUrl,
  } = props
  const [initError, setInitError] = useState<Error | string>()
  const [state, setState] = useState<State>({
    localSpaceId: '',
    accessTokenLocal: '',
    spaceUrl: '',
  })
  const [closeInstance, setCloseInstance] = useState<boolean>(false)

  const { localSpaceId, spaceUrl, accessTokenLocal } = state

  const initSpace = async () => {
    setCloseInstance(false)
    try {
      const existingSpace = props.space && props.space.id
      const result =
        props.publishableKey && !existingSpace
          ? await initializeSpace(props as SimpleOnboarding)
          : await getSpace(props as ReusedSpaceWithAccessToken)

      const data = result?.space?.data

      if (!data) {
        throw new Error('Failed to initialize space')
      }

      const { id: spaceId, accessToken, guestLink } = data

      if (!spaceId) {
        throw new Error('Missing spaceId from space response')
      }

      if (!guestLink) {
        throw new Error('Missing guest link from space response')
      }

      setState((prevState) => ({
        ...prevState,
        localSpaceId: spaceId,
        spaceUrl: guestLink,
      }))

      if (!accessToken) {
        throw new Error('Missing access token from space response')
      }

      setState((prevState) => ({
        ...prevState,
        accessTokenLocal: accessToken,
      }))
    } catch (error: any) {
      setInitError(error)
    }
  }

  useEffect(() => {
    initSpace()
  }, [])

  const errorElement = ErrorElement ? (
    // Adding non-null assertion because this will never be hit if error is falsy, ts is unhappy.
    ErrorElement(initError!)
  ) : (
    <DefaultError error={errorTitle || initError!} />
  )

  const loadingElement = LoadingElement ?? (
    <div style={{ margin: '16px' }}>
      <Spinner />
    </div>
  )

  if (initError) {
    return errorElement
  }

  if (closeInstance) {
    return null
  } 

  if (localSpaceId && spaceUrl && accessTokenLocal) {
    return (
      <Space
        key={localSpaceId}
        spaceId={localSpaceId}
        spaceUrl={spaceUrl}
        accessToken={accessTokenLocal}
        handleCloseInstance={() => setCloseInstance(true)}
        {...props}
      />
    )
  }

  return loadingElement
}

export default useSpace

// packages/vue/src/components/UseSpace.vue
<template>
  <div>
    <DefaultError v-if="initError" :error="initError" />
    <SpaceC
      v-if="localSpaceId && spaceUrl && accessTokenLocal"
      :spaceId="localSpaceId"
      :spaceUrl="spaceUrl"
      :accessToken="accessTokenLocal"
      :apiUrl="apiUrl"
      :displayAsModal="displayAsModal"
      :exitText="exitText"
      :exitTitle="exitTitle"
      :workbook="createdWorkbook"
      :exitPrimaryButtonText="exitPrimaryButtonText"
      :exitSecondaryButtonText="exitSecondaryButtonText"
      :closeSpace="closeSpace"
      :listener="listener"
      :sidebarConfig="sidebarConfig"
      :spaceInfo="spaceInfo"
      :userInfo="userInfo"
      :document="document"
      :themeConfig="themeConfig"
      :environmentId="environmentId"
      :iframeStyles="iframeStyles"
      :onSubmit="onSubmit"
      :onRecordHook="onRecordHook"
    />
    <SpinnerC v-else></SpinnerC>
  </div>
</template>

<script>
import { ref, onMounted } from 'vue'
import useInitializeSpace from '../utils/useInitializeSpace'
import {
  getSpace
} from '@flatfile/embedded-utils'
import SpaceC from './SpaceC.vue'
import SpinnerC from './Spinner.vue'
import DefaultError from './DefaultError.vue'

export default {
  props: {
    name: String,
    publishableKey: String,
    environmentId: String,
    closeSpace: Object,
    space: Object,
    themeConfig: Object,
    listener: Object,
    sidebarConfig: Object,
    document: Object,
    sheet: Object,
    spaceBody: Object,
    spaceInfo: Object,
    userInfo: Object,
    workbook: Object,
    onRecordHook: Function,
    onSubmit: Function,
    displayAsModal: Boolean,
    iframeStyles: Object,
    mountElement: {
      type: String,
      default: 'flatfile_iFrameContainer',
    },
    exitText: {
      type: String,
      default:
        'Are you sure you want to exit? Any unsaved changes will be lost.',
    },
    exitTitle: {
      type: String,
      default: 'Close Window',
    },
    exitPrimaryButtonText: {
      type: String,
      default: 'Yes, exit',
    },
    exitSecondaryButtonText: {
      type: String,
      default: 'No, stay',
    },
    apiUrl: {
      type: String,
      default: 'https://platform.flatfile.com/api',
    },
  },
  setup(props) {
    const { initializeSpace, createdWorkbook } = useInitializeSpace(props)
    const initError = ref(null)
    const localSpaceId = ref(null)
    const accessTokenLocal = ref(null)
    const spaceUrl = ref('')

    const initSpace = async () => {
      try {
        const data = props.publishableKey
          ? await initializeSpace(props)
          : await getSpace(props)

        if (!data) {
          throw new Error('Failed to initialize space')
        }

        const { id: spaceId, accessToken, guestLink } = data.data

        if (!spaceId) {
          throw new Error('Missing spaceId from space response')
        }

        if (!guestLink) {
          throw new Error('Missing guest link from space response')
        }

        if (!accessToken) {
          throw new Error('Missing access token from space response')
        }

        localSpaceId.value = spaceId
        spaceUrl.value = guestLink
        accessTokenLocal.value = accessToken
      } catch (error) {
        initError.value = error.message
      }
    }

    onMounted(() => {
      initSpace()
    })

    return {
      initSpace,
      initError,
      localSpaceId,
      spaceUrl,
      accessTokenLocal,
      createdWorkbook,
    }
  },
  components: {
    SpaceC,
    SpinnerC,
    DefaultError,
  },
}
</script>

<style lang="css">
@import url(./../main.css);
</style>
